spring.application.name=kafkaOrderService


server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/KafkaEcomerceProject
spring.datasource.username=postgres
spring.datasource.password=Jyoti@123

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.kafka.bootstrap-servers=localhost:9092